spring :

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/cache
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto:  create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
